import { Inter } from "next/font/google";
import "./globals.css";
import NavBarDrawer from "./components/navBar/page";
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import webTheme from "./theme";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Power Division",
  description: "Generated by create next app",
};

const drawerWidth = 223;

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={webTheme}>
          {/* <CssBaseline/> */}
            <NavBarDrawer></NavBarDrawer>
          <Box sx={{mt:10,
            ml: {xs:2, md: `${drawerWidth}px` }, mr: {xs:2,md: 3}}}>
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
