"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarDrawer from "./components/navBar/page";
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import webTheme from "./theme";
import React from "react";
import CurrentRoute from "./components/currentRoute/page";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Power Division",
//   description: "Generated by create next app",
// };

const drawerWidth = 223;

export default function RootLayout({ children }) {
  const pathname = usePathname();
  console.log(".......", pathname);

  const noNavbar = pathname.includes("login");

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={webTheme}>
          <CssBaseline />

          {noNavbar || <NavBarDrawer></NavBarDrawer>}
          <Box
            sx={{
              mt: 10,
              ml: { xs: 2, md: `${drawerWidth}px` },
              mr: { xs: 2, md: 3 },
            }}
          >
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
