import { Inter } from "next/font/google";
import "./globals.css";
import NavBarDrawer from "./components/navBar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Power Division",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <NavBarDrawer >

          {children}
        </NavBarDrawer>
        </body>
    </html>
  );
}
